import PageHero from "@/locales/de/components/PageHero";
import CTA from "@/locales/de/components/CTA";
import { metadataForRoute } from '@/lib/seo';
export const metadata = metadataForRoute('de', '/company');
export default function CompanyPage() {
  return <>
      <PageHero eyebrow={"Wie PayMyDine gestaltet ist"} title={"Eine Restaurantplattform organisierte 9 Produktjobs, 6 Rollenarbeitsbereiche und einen gemeinsamen Betriebskontext."} intro={"PayMyDine trennt die Verantwortlichkeiten, ohne das Restaurant zu trennen. Gastaktionen, Teamwarteschlangen, Küchenstatus, Zahlungs- und Managementmetriken können verbunden bleiben, während jede Person die für den Job relevanten Kontrollen sieht."} image="/site-assets/extra/team-tech-meeting.webp" accent="green" />
      <section className="section companyValues"><div className="container companyValuesGrid"><div><span className="eyebrow">Vier Produktregeln</span><h2>Jedes Feature sollte beantworten, wer handelt, welcher Kontext erforderlich ist, welcher Status den Abschluss belegt und welche Metriken sich ändern.</h2><p>Dies hält das Produkt in der Restaurantarbeit verankert, anstatt eine Sammlung von getrennten Dashboards und Marketing-Claims zu erstellen.</p></div><div className="companyValueCards"><article><h3>Rollenbesitz</h3><p>Eigentümer, Manager, Servicemitarbeiter, Küche, Reservierungen und Finanzen erhalten gezielte Kontrollen und Genehmigungen.</p></article><article><h3>Gemeinsamer Kontext</h3><p>Tisch, Gast, Bestellung, Timing und Zahlungskontext können über die Übergabe reisen, anstatt erneut eingegeben zu werden.</p></article><article><h3>Gemessene Workflows</h3><p>Jedes Setup identifiziert Baseline- und Zielmetriken wie Wartezeit, Vorbereitungszeit, Umsatz, durchschnittliche Prüf- oder Wiederholungsrate.</p></article><article><h3>KI mit Source-Sichtbarkeit</h3><p>KI kann verfügbare Daten zusammenfassen und vergleichen, aber die Quellansicht und die menschliche Entscheidung bleiben sichtbar.</p></article></div></div></section>
      <section className="section companyGallery"><div className="container companyGalleryGrid"><img src="/site-assets/extra/cafe-exchange.webp" alt="" /><img src="/site-assets/extra/cafe-professional.webp" alt="" /><img src="/site-assets/extra/chef-gourmet.webp" alt="" /><img src="/site-assets/extra/rooftop-dinner.webp" alt="" /></div></section>
      <CTA title={"Bewerten Sie PayMyDine mit einem echten Restaurant-Workflow, nicht mit einer generischen Feature-Liste."} body={"Bringen Sie die Rollen, aktuellen Systeme, wiederholte Arbeit und Metriken hinter ein Betriebsproblem. Wir werden die relevanten Produktbereiche und Grenzen abbilden."} />
    </>;
}
